### ISSUE TITLE
Refused to execute do to MIME type

### ISSUE THREAD

**Issue by tommyc38** [MurhafSousli/ngx-highlightjs#34]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Sierra 10.12.6

### Versions

Package                           Version
-----------------------------------------------------------
angular-devkit/architect         0.6.3
angular-devkit/build-angular     0.6.3
angular-devkit/build-optimizer   0.6.3
angular-devkit/core              0.6.3
angular-devkit/schematics        0.6.3
angular/cli                      6.0.3
angular/flex-layout              6.0.0-beta.15
ngtools/webpack                  6.0.3
schematics/angular               0.6.3
schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

I copied your stackblitz code directly but get these errors in the console:

Refused to apply style from 'http://localhost:4200/assets/lib/hljs/styles/github.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Refused to execute script from 'http://localhost:4200/assets/lib/hljs/highlight.pack.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### Mention any other details that might be useful

Looks like its related to https://github.com/angular/angular-cli/issues/10325

**Comment by MurhafSousli** [comment]
I guess it is related to the issue you pointed out, did you try to load them in `index.html` instead?

**Comment by tommyc38** [comment]
@MurhafSousli I fixed it by adding github.css and highlight.pack.js into angular.json (app styles and scripts arrays)

**Comment by adamdoyle** [comment]
@tommyc38 I know this is old, but did adding `github.css` to your `styles` array in `angular.json` actually remove the error from the console, or did it only fix the style?  For me, it's only fixing the style, and (ideally) I'd like to get rid of the error as well.

My understanding is that with this approach the browser attempts to load the style from two places: **(1)** Angular CLI is bundling everything from the `styles` array in `angular.json` into `styles.js`, and **(2)** `highlight.service.ts:_themeLoader()` is dynamically inserting a `<link>` element at runtime to pull the styles from `${this.options.path}/styles/github.css`.

The browser succeeds at loading the style with `method (1)`, but fails for `method (2)`.  Since one of the two methods succeeded, the page renders correctly, but the extraneous failed `<link>` results in a console error.

@MurhafSousli To your knowledge, is there a mechanism in place for configuring `ngx-highlightjs` to not add the `<link>` tag and assume the consumer of the library is providing the styles on his or her own?

I tried `HighlightModule.forRoot({path: '#'})`, resulting in `<link rel="stylesheet" type="text/css" href="#/styles/github.css">`, which technically appeared to work (suppressed error messages and rendered the styles on-screen correctly), but probably isn't optimal as it leaves behind a dummy `<link>` element and probably leaves something similar for the Javascript.

**Comment by MurhafSousli** [comment]
@adamdoyle track this #56
